// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qukozdugcpmuemsxijtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1a296ZHVnY3BtdWVtc3hpanRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4NDcyNDYsImV4cCI6MjA4NDQyMzI0Nn0.9srWd2R2uBGpPQdx-Xs9ztUC31rzyNCHLTy3BTQybi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
